<table style="width:100%" id="phpContent">
	<tr>
		<td style="width:350px;vertical-align:top;">
			<div id='leftPanel'>
				<div id="P1L1">
					<fieldset>
						<legend><?php echo $this->translate('search');?></legend>
						<div style="float:left;">
							<input type="text" id="searchContent" class="jqxinput" prop="{'placeHolder':'Enter Key Value.', width:200}"/>
						</div>
						<div style="float: right;">
							<input type="button" value="<?php echo $this->translate('search');?>" id='jqxButton' class="jqxButton" prop="{'width':90,'imgSrc':'search.png'}"/>
						</div>
					</fieldset>
				</div>
				
				<div id="P1L2">
					<fieldset>
						<legend id="P1S2-Title" class="yacePointer icon-expand"><?php echo $this->translate('docInfo');?></legend>
						<table id="P1S2-Main" cellspacing="0" cellpadding="0" style="width:100%;">
							<tbody>
								<tr>
									<td class="yaceWidth20"><?php echo $this->translate('docName');?></td>
									<td colspan="2">
										<input type="text" id="ymc_localName" class="jqxinput"/>
									</td>
								</tr>
								<tr>
									<td class="yaceWidth20"><?php echo $this->translate('creator');?></td>
									<td >
										<input type="text" id="ymc_creator" class="jqxinput"/>
									</td>
									<td >
										<input type="button" value="<?php echo $this->translate('select');?>" id='personSearch' class="jqxButton" prop="{'width':65}"/>
									</td>
								</tr>
							</tbody>
						</table>
					</fieldset>
				</div>
				
				<div id="P1L3">
					<fieldset>
						<legend id="P1S2-Title" class="yacePointer icon-expand"><?php echo $this->translate('tree');?></legend>
						<div id='jqxTree'>
						</div>
					</fieldset>
				</div>
			</div>
		</td>
		<td style="vertical-align:top;">
			<div id='rightPanel'>
				<span>DataBase1</span>
				<table style="width:100%;">
					<tbody>
					<?php foreach($this->compModels as $compModel): ?>
						<tr>
							<td >
							    <div class="blog-title">
							        <?php echo $compModel["compid"]; ?>
							    </div>
						    </td>
						    <td>
							    <div class="blog-content">
							        <?php echo $compModel["compnmlocal"]; ?>
							    </div>
						    </td>
						</div>
						</tr>
					<?php endforeach; ?>
					</tbody>
				</table>
				<br>
				<span>DataBase2</span>
				<table style="width:100%;">
					<tbody>
					<?php foreach($this->orgModels as $orgModel): ?>
						<tr>
							<td >
							    <div class="blog-title">
							        <?php echo $orgModel["code"]; ?>
							    </div>
						    </td>
						    <td>
							    <div class="blog-content">
							        <?php echo $orgModel["codename"]; ?>
							    </div>
						    </td>
						</div>
						</tr>
					<?php endforeach; ?>
					</tbody>
				</table>
			</div>
		</td>
	</tr>
</table>

<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/project/demo/demo.js"></script>
<link href="<?php echo $this->baseUrl() ?>/project/demo/demo.css" media="screen" rel="stylesheet" type="text/css" >